spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: desafio-cdc
      auto-index-creation: true
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: America/Sao_Paulo

logging:
  level:
    dev.desafiocdc: DEBUG
